### ISSUE TITLE
Control internal volume while DP monitor is the default sound output device

### ISSUE THREAD

**Issue by marcvangend** [MonitorControl/MonitorControl#618]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

When an external monitor is selected in Preferences > Sound as the default sound output device, MacOS disables the volume control of the internal speakers. Still, some apps can choose (or be configured) to play audio over the internal speakers. (I personally prefer this for video calls and notifications.)

I installed MonitorControl hoping that it would also allow me to control the internal speaker volume, just like you can control the volume of external monitors. As far as I can see this is not supported yet.

Currently I'm using the build from https://github.com/MonitorControl/MonitorControl/issues/539#issuecomment-912826766 on a 2017 MBP with Big Sur.

### Describe the solution you'd like

I would like to be able to control the internal speaker volume, even when it is not the default sound output device.

### Describe alternatives you've considered

I have looked at other applications - no luck.

### Anything else?

![Screenshot_2021-09-24_at_12_08_43](https://user-images.githubusercontent.com/315224/134658234-a606df55-1ec7-4424-8dc2-28d7026bcbff.jpg)

**Comment by waydabber** [comment]
Hi @marcvangend 

cool! Happy to see 4.0.0 apparently work well on an Intel mac as I didn't even try that yet. :) If you encounter any issues with the build, please let me know in the 4.0.0 discussion!

About the request:

The idea is valid, but I am afraid the problem becomes complex rather soon. If there is an external speaker connected to the macbook via the jack port, the user would expect that to be controlled (as some users expect external speaker connected to a display to be controlled). But what if it is an USB speaker? If we cover that, why not a bluetooth device? Or an airplay one? The problem would be a significant increase in the scope of the app. If there are several audio devices (on my mac there are six at the moment), it will be very difficult to figure out which one should be associated with the built-in display. We could maybe add a setting to associate an audio device with the internal display (as there is such a setting for the external display now).

Btw, there are apps that allow you to control audio outputs individually (aside from the built-in Audio MIDI Setup), probably https://rogueamoeba.com/soundsource/ can do this, but I did not try.

**Comment by marcvangend** [comment]
Hi @waydabber, thanks for the swift reply. I'm happy I helped you test the new version without even knowing it ;-) I'll let you know if I find any issues.

I see your point... as simple as my request seems when I wrote it, I understand why you would choose to not open that can of worms.

Regarding SoundSource: I did see it, but I didn't try it out. It seems to add a lot of features and complexity. It may be worth its price when you need all that, but I'm not keen on spending $48 when all I really want is one volume slider.

**Comment by waydabber** [comment]
I'll look into this I think. Since there is already an `Override audio device name` option under Displays/Advanced, we could make it enabled for Apple/built in displays and if `SimplyCoreAudio` is able to change the volume of a non-default audio device addressed by device name, then this feature silently be added for the benefit of tinkering users (without further complicating the UI which is already complicated thanks to the plethora of  new feature requests implemented... :)).

**Comment by JoniVR** [comment]
Yeah I think we can just add sliders for devices that can set their own volume (in theory), I know SimplyCoreAudio supports the check, because we already use it somewhere (or at least used to).

**Comment by mustefa** [comment]
+1, I'm exploring solutions right now and came across this issue. Volume control of external monitor would be amazing.

**Comment by waydabber** [comment]
@mustefa - MonitorControl provides volume control for external monitors via DDC. :)

**Comment by 3dinhjeffrey** [comment]
Hi, I would like to know how I can change the volume of my external speakers. I tried the steps:

1) Override audio device name -> click Get current. It populated my external speakers. 

But it still cannot control the volume. What can I do to control the speakers? Would like to have MonitorControl as my one stop menu bar icon to control monitor brightness and volume (external monitor and external speakers not from the monitor). Thanks!

@waydabber 


> I'll look into this I think. Since there is already an `Override audio device name` option under Displays/Advanced, we could make it enabled for Apple/built in displays and if `SimplyCoreAudio` is able to change the volume of a non-default audio device addressed by device name, then this feature silently be added for the benefit of tinkering users (without further complicating the UI which is already complicated thanks to the plethora of new feature requests implemented... :)).

**Comment by waydabber** [comment]
Hi @3dinhjeffrey,

MonitorControl is not equipped at this time to control the volume of audio devices that can be controlled by macOS itself, it was made to control Displays which cannot be controlled by macOS natively using a protocol called DDC/CI (Display Data Channel Command Interface -  is a communication protocol to control displays). The `Override audio device name` was made to assume control of a display even when the default output device is not the display itself but a software audio device driver that can control tone for example (like [Boom3D](https://www.globaldelight.com/boom/) for example) which in turn still routes the audio to the display eventually (but in a way that is not detectable to MonitorControl).

The current feature request `Control internal volume while DP monitor is the default sound output device` is about making the app control the volume of outputs that are natively supported by macOS (providing the needed feature for your use case), but this feature is not implemented yet in 4.0.0.

Hope this clarifies things!

**Comment by 3dinhjeffrey** [comment]
Thanks for the clear explanation, understood! @waydabber

**Comment by joehquak** [comment]
Hey @JoniVR 😁 
Did you have any luck with progressing on this? 🙏
